### ISSUE TITLE
打开iframe跨域访问问题

### ISSUE THREAD

**Issue by jackcailj** [bhuh12/vue-router-tab#9]
调用this.$routerTab.openIframeTab('https://www.baidu.com', '百度', 'icon-web')报错，帮看看什么问题

 Uncaught DOMException: Blocked a frame with origin "https://www.baidu.com" from accessing a cross-origin frame.
    at HTMLDocument.t (https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/static/protocol/https/global/js/all_async_search_2345059.js:181:309)
    at i (https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/js/lib/jquery-1.10.2_1c4228b8.js:25:20711)
    at Object.fireWith [as resolveWith] (https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/js/lib/jquery-1.10.2_1c4228b8.js:25:21615)
    at Function.ready (https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/js/lib/jquery-1.10.2_1c4228b8.js:14:3609)
    at HTMLDocument.cP (https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/js/lib/jquery-1.10.2_1c4228b8.js:14:769)
t @ all_async_search_2345059.js:181
i @ jquery-1.10.2_1c4228b8.js:25
fireWith @ jquery-1.10.2_1c4228b8.js:25
ready @ jquery-1.10.2_1c4228b8.js:14
cP @ jquery-1.10.2_1c4228b8.js:14

**Comment by bhuh12** [comment]
应该是百度的js有试图访问你主页面dom的操作，被浏览器跨域限制了。这个确切来说不算是问题，是浏览器的安全策略。如果有权限跨域操作才是不应该的。

正常的需求场景是嵌入的iframe页面和主页面双方通讯。可以通过postMessage来实现，需要两个系统协作完成。这个你可以自行百度试试。

你也可以试试多嵌入几个其他网站试试，看是否都有这样的报错。

**Comment by jackcailj** [comment]
谢谢反馈，打开百度确实会包报这个错误，但是能打开，之所以查看到这个问题是因为openIframeTab时，页签内容没有显示，跟踪一下发现，router-tab这个class高度为0，增加height:100%后可以了。

**Comment by bhuh12** [comment]
好的，我样式也优化一下，到时候加个最小高度
